services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-client
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # Access MinIO from host via localhost:9000
      - "9001:9001"  # Access MinIO Console from host via localhost:9001
    # volumes:
    #   - minio_data:/data
    networks:
      - shared_network

  client:
    build: ./
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    #volumes:
     # - minio_data:/data
    networks:
      - shared_network
     
networks:
  shared_network:
    external: true

# volumes:
#   minio_data:
