version: "3.9"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # Access MinIO from host via localhost:9000
      - "9001:9001"  # Access MinIO Console from host via localhost:9001
    # volumes:
    #   - minio_data:/data

  minio-init:
    build: ./minio-init
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    #volumes:
     # - minio_data:/data

  orchestrator:
    build: ./orchestrator
    working_dir: /app
    volumes:
      - ./orchestrator:/app
    ports:
      - "3000:3000"  # Access Orchestrator from host via localhost:3000
    command: ["node", "--watch", "orchestrator.mjs"]
    depends_on:
      - minio

# volumes:
#   minio_data:
