services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    command: server /data

  minio-init:
    build: ./minio-init  
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  orchestrator:
    build: ./orchestrator  
    working_dir: /app
    volumes:
      - ./orchestrator:/app
    ports:
      - "8080:8080"
    command: ["node", "--watch", "orchestrator.mjs"]


volumes:
  minio_data:
  server_data:
